### ISSUE TITLE
Could you tell me how to use this drive for our job？

### ISSUE THREAD

**Issue by pangchenglin** [JeongJae0815/Multi_Velodyne#1]
I want to use 2 velodyne vlp-16 like you.But I don't konw how to use your drive.Could please tell me how to use of it?Many thanks

**Comment by j2pory** [comment]
sorry for replying so late. 
this repo was maded for my own usage, so I haven't expected someone would refer. 
I edited the Readme file for usage of multiple velodyne, so you can check how to use multiple devices on ros.
